export const type = {
    ROOM_CREATE: {
        RESPONSE_FAILURE: "ROOM_CREATE_RESPONSE_FAILURE",
        RESPONSE_SUCCESS: "ROOM_CREATE_RESPONSE_SUCCESS",
    },
    ROOM_DESTROY:{
        RESPONSE_FAILURE: "ROOM_DESTROY_RESPONSE_FAILURE",
        RESPONSE_SUCCESS: "ROOM_DESTROY_RESPONSE_SUCCESS",
    },
    ROOM_JOIN:{
        RESPONSE_SUCCESS: "JOIN_ROOM_RESPONSE_SUCCESS",
        RESPONSE_FAILURE: "JOIN_ROOM_RESPONSE_FAILURE",
        REQUEST: "JOIN_ROOM_REQUEST",
        NOTIFY: "JOIN_ROOM_NOTIFY",
    },
    ROOM_EXIT:{
        REQUEST: "EXIT_ROOM_REQUEST",
        NOTIFY: "EXIT_ROOM_NOTIFY",
    },
    ROOM_DISCONNECT:{
        NOTIFY: "DISCONNECT_ROOM_NOTIFICATION",
    },
    WEB_RTC:{
        OFFER: "OFFER",
        ANSWER: "ANSWER",
        ICE_CANDIDATE: "ICE_CANDIDATE",
    }
}
export const label = {
    NORMAL_SERVER_PROCESS: "NORMAL_SERVER_PROCESS",
    WEBRTC_PROCESS: "WEBRTC_PROCESS",
}